import { AboutPage } from "@/components";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function Home() {
  return <AboutPage />;
}
