import { ProjectPage } from "@/components";

export const metadata = {
  title: "Projects",
  description: "Generated by create next app",
};

export default function Home() {
  return <ProjectPage />;
}
