import { Contact, Hero, Projects, Technologies } from "@/components";

export const metadata = {
  title: "Aymane Portfolio",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <Hero />
      <Projects />
      <Technologies />
      <Contact />
    </main>
  );
}
