export { default as Navbar } from "./Navbar";
export { default as Footer } from "./Footer";
export { default as Hero } from "./Hero";
export { default as Projects } from "./Projects";
export { default as ProjectCard } from "./subcomponent/ProjectCard";
export { default as Technologies } from "./Technologies";
export { default as Contact } from "./Contact";
export { default as ProjectPage } from "./ProjectPage";
export { default as AboutPage } from "./AboutPage";
